Greatly improves the navbar
tgstation/tgstation-server-control-panel pull request #101
Opened 2022-08-27 13:20 UTC by AffectedArc07

The current system is honestly the **worst** UI/UX I have ever used, and no, I am not being hyperbolic.

---
Before
![chrome_04bIs4ycMx](https://user-images.githubusercontent.com/25063394/187032047-063630f1-fa34-4953-a5b1-ad50e8f05774.gif)

After
![chrome_3HQuamfDj4](https://user-images.githubusercontent.com/25063394/187032024-73898391-7e83-4e7f-a9ec-177a496ec927.gif)

2022-08-27 14:47 UTC, AffectedArc07 commented
Turns out I forgot functionality

2022-08-28 11:46 UTC, AffectedArc07 commented
![image](https://user-images.githubusercontent.com/25063394/187072566-b1f3b636-6db4-4310-a59b-76d19a768a9a.png)
![image](https://user-images.githubusercontent.com/25063394/187072574-43041115-c6cc-4644-a6cf-0a1cd77c0e5c.png)
![image](https://user-images.githubusercontent.com/25063394/187072579-0109b676-af86-4369-875c-bce98e872a59.png)
![image](https://user-images.githubusercontent.com/25063394/187072580-bf96899c-3779-4ecc-81c3-8782d2ba794d.png)

2022-08-28 17:20 UTC, alexkar598 requested changes

2022-08-28 17:20 UTC, alexkar598 commented on src/components/AppNavbar.tsx
> -                                                        focusTimer: undefined
Remove the state variables if they arent going to be used anymore

2022-08-28 18:17 UTC, alexkar598 approved these changes

2022-08-28 18:17 UTC, merged