Repository clone page
tgstation/tgstation-server-control-panel pull request #34
Opened 2021-02-25 23:43 UTC by Cyberboss

![image](https://user-images.githubusercontent.com/8171642/109234193-3bafa300-7799-11eb-9a6d-db2c22a4e635.png)

Also:

- Implements some of the RepositoryClient.
- Allows the navbar to show TGS version without logging in.
- Adds a JobsController method to register received jobs immediately..

2021-03-07 02:44 UTC, Cyberboss commented
![image](https://cdn.discordapp.com/attachments/484170915253321734/817948515979362304/unknown.png)

2021-03-07 03:03 UTC, Cyberboss commented
![image](https://user-images.githubusercontent.com/8171642/110227579-c3975a80-7ec7-11eb-9648-54991df6301f.png)

2021-03-07 03:03 UTC, Cyberboss commented
> 
> 
> ![image](https://camo.githubusercontent.com/ca64fd7c3f4dd5a7d401db6fce2e08c95df118749344bf48738fdbc82b991746/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3438343137303931353235333332313733342f3831373934383531353937393336323330342f756e6b6e6f776e2e706e67)

Deploy check is now at top of page here

2021-03-23 04:14 UTC, alexkar598 requested changes
Still need to review the main file

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/RepositoryClient.ts
> +            }
This will be handled within the catch block and wont ever execute

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/RepositoryClient.ts
> +            default: {
code 410 is unhandled

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/RepositoryClient.ts
> +            }
Handled within catch block and never executed

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/RepositoryClient.ts
> +            default: {
Code 410 is missing

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/RepositoryClient.ts
> +            case 202: {
Not 100% sure about how jobs and repositories work but you might have to do JobsController.restartLoop() here to catch and display new jobs

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/RepositoryClient.ts
> +            default: {
Code 410 not handled

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/RepositoryClient.ts
> +            default: {
410 not handled

2021-03-23 04:14 UTC, alexkar598 commented on src/ApiClient/util/config.ts
> +        id: "config.testmergelabel",
Localization string is missing

2021-03-23 04:14 UTC, alexkar598 commented on src/components/AppNavbar.tsx
> -                await this.loadServerInformation();
Why not move this outside the if check? Also remove line 103 with the login hook for server info. dont think thats needed anymore

2021-03-23 04:14 UTC, alexkar598 commented on src/utils/routes.ts
> +    selectedinstancetab: undefined as undefined | string,
Not used anywhere

2021-04-01 16:22 UTC, closed without merging